name: study_planner_exam_tracker
description: App Flutter per pianificare studio, esami, corsi, attività e obiettivi universitari.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  forui: ^0.21.3

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
